;【設定ファイル】
;設定.iniを直接編集する場合は、アプリが起動していない状態にしてください。
;アプリ起動中は、右クリックメニューの「設定」から編集可能です。
;
;撮影画像の保存先を指定してください。
DestinationPath=C:\Users\User\Pictures\Camera Roll
;
;カメラのシャッターが切れる前に終了してしまう場合は
;こちらの値を大きくしてみてください。(ミリ秒)
WaitBeforeReleaseShutter=1
;
;撮影後の画像が日付フォルダにうまく移動されない場合は
;こちらの値を大きくしてみてください。(ミリ秒)
WaitAfterReleaseShutter=1
;
;最初のシャッターでうまく撮影できなかった場合に
;リトライする回数を設定できます。
RetryCount=4
;
;保存先に存在する○ヶ月前のフォルダを削除する機能を有効にします。
EnableDeleteLimit=True
;
;以下で指定したよりも古いフォルダを削除します。
DeleteLimitMonth=6
;
;最前面に実行ボタンを表示できます。(True / False)
EnableFloatingButton=True
;
;カメラアプリを都度閉じます。(True / False)
CloseCamera=False
;
;カメラアプリを閉じない場合に最小化します。(True / False)
MinimizeCamera=True
;
;撮影時に薬歴アプリで開かれている患者名をファイル名に追加します。(True / False)
AddPatientName=True
;
;表示位置
WindowX=580
WindowY=645
;
;表示サイズ
Width=149
Height=101
